import React, { createContext, useState, useContext, useEffect, useRef } from 'react';
import { useAuth } from './AuthContext';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

// ===== العملات المدعومة =====
export const SUPPORTED_CURRENCIES = {
  USD: { code: 'USD', symbol: '$', name: 'دولار أمريكي', rate: 1, flag: '🇺🇸' },
  EUR: { code: 'EUR', symbol: '€', name: 'يورو', rate: 0.92, flag: '🇪🇺' },
  GBP: { code: 'GBP', symbol: '£', name: 'جنيه إسترليني', rate: 0.79, flag: '🇬🇧' },
  DZD: { code: 'DZD', symbol: 'دج', name: 'دينار جزائري', rate: 135.0, flag: '🇩🇿' },
  SAR: { code: 'SAR', symbol: 'ر.س', name: 'ريال سعودي', rate: 3.75, flag: '🇸🇦' },
  AED: { code: 'AED', symbol: 'د.إ', name: 'درهم إماراتي', rate: 3.67, flag: '🇦🇪' },
  BTC: { code: 'BTC', symbol: '₿', name: 'بيتكوين', rate: 0.000015, flag: '₿' },
  ETH: { code: 'ETH', symbol: 'Ξ', name: 'إيثريوم', rate: 0.00023, flag: 'Ξ' },
  USDT: { code: 'USDT', symbol: '₮', name: 'Tether', rate: 1, flag: '₮' },
};

// ===== اللغات المدعومة مع الأعلام =====
export const SUPPORTED_LANGUAGES = {
  ar: {
    code: 'ar',
    name: 'العربية (الجزائر)',
    flag: '🇩🇿',
    dir: 'rtl',
  },
  en: {
    code: 'en',
    name: 'English (UK)',
    flag: '🇬🇧',
    dir: 'ltr',
  },
  fr: {
    code: 'fr',
    name: 'Français (France)',
    flag: '🇫🇷',
    dir: 'ltr',
  },
};

// ===== الترجمات الكاملة =====
const translations = {
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.shop': 'المتجر',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    'nav.support': 'الدعم',
    'nav.faq': 'الأسئلة الشائعة',
    'nav.topup': 'شحن ألعاب',
    'nav.giftcards': 'بطاقات هدايا',
    'nav.cdkeys': 'مفاتيح CD',
    'nav.gamecards': 'اشتراكات',
    'nav.recharge': 'شحن سريع',
    'nav.wishlist': 'المفضلة',
    'nav.cart': 'السلة',
    'nav.login': 'تسجيل الدخول',
    'nav.register': 'حساب جديد',
    'nav.logout': 'خروج',
    'nav.search': 'بحث',
    'nav.search_placeholder': 'ابحث عن شحن، بطاقات، مفاتيح ألعاب...',
    'nav.dashboard': 'لوحتي',
    'nav.seller_dashboard': 'لوحة البائع',
    'nav.currency': 'العملة',
    'nav.language': 'اللغة',
    'nav.wallet': 'المحفظة',
    'nav.my_account': 'حسابي',
    'nav.my_orders': 'طلباتي',
    'nav.light_mode': 'الوضع النهاري',
    'nav.dark_mode': 'الوضع الليلي',
    'nav.instant_delivery': 'توصيل فوري 24/7',
    'nav.security': 'حماية 100%',
    'nav.live_support': 'دعم مباشر 24/7',
    'nav.free_shipping': 'شحن مجاني للطلبات فوق $50',
    'nav.system': 'النظام',
    'nav.profile': 'الملف الشخصي',
    'nav.reports': 'التقارير',
    'nav.admin_panel': 'لوحة التحكم',
    'nav.system_admin': 'مدير النظام',
    
    // Common
    'common.add_to_cart': 'أضف للسلة',
    'common.buy_now': 'شراء الآن',
    'common.out_of_stock': 'نفد',
    'common.in_stock': 'متوفر',
    'common.only_left': 'متبقي',
    'common.quick_view': 'معاينة سريعة',
    'common.view_all': 'عرض الكل',
    'common.total': 'الإجمالي',
    'common.checkout': 'إتمام الشراء',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.close': 'إغلاق',
    'common.back': 'رجوع',
    'common.continue': 'متابعة',
    'common.loading': 'جاري التحميل...',
    'common.no_results': 'لا توجد نتائج',
    'common.search_results': 'نتائج البحث',
    'common.secure_payment': 'مدفوعات آمنة 100%',
    'common.copied': 'تم النسخ',
    'common.share': 'مشاركة',
    
    // Product
    'product.price': 'السعر',
    'product.platform': 'المنصة',
    'product.delivery': 'التوصيل',
    'product.stock': 'المخزون',
    'product.rating': 'التقييم',
    'product.reviews': 'مراجعات',
    'product.description': 'وصف المنتج',
    'product.seller': 'البائع',
    'product.quantity': 'الكمية',
    'product.discount': 'خصم',
    
    // Auth
    'auth.login_title': 'تسجيل الدخول',
    'auth.login_desc': 'مرحباً بعودتك! قم بتسجيل الدخول إلى حسابك',
    'auth.register_title': 'إنشاء حساب',
    'auth.register_desc': 'انضم إلى CTGPRO واستمتع بتجربة شحن فريدة',
    'auth.email_or_phone': 'البريد الإلكتروني أو رقم الهاتف',
    'auth.password': 'كلمة المرور',
    'auth.confirm_password': 'تأكيد كلمة المرور',
    'auth.remember_me': 'تذكرني',
    'auth.forgot_password': 'نسيت كلمة المرور؟',
    'auth.no_account': 'ليس لديك حساب؟',
    'auth.have_account': 'لديك حساب بالفعل؟',
    'auth.full_name': 'الاسم الكامل',
    'auth.phone': 'رقم الهاتف',
    'auth.reset_password': 'إعادة تعيين كلمة المرور',
    'auth.reset_password_desc': 'أدخل كلمة المرور الجديدة',
    
    // Profile
    'profile.title': 'الملف الشخصي',
    'profile.personal_info': 'المعلومات الشخصية',
    'profile.full_name': 'الاسم الكامل',
    'profile.phone': 'رقم الهاتف',
    'profile.email': 'البريد الإلكتروني',
    'profile.address': 'العنوان',
    'profile.street': 'الشارع',
    'profile.city': 'المدينة',
    'profile.state': 'الولاية',
    'profile.zip_code': 'الرمز البريدي',
    'profile.country': 'الدولة',
    'profile.account_preferences': 'تفضيلات الحساب',
    'profile.language': 'اللغة',
    'profile.currency': 'العملة',
    'profile.theme': 'الوضع',
    'profile.notifications': 'إشعارات الحساب',
    'profile.save_changes': 'حفظ التغييرات',
    'profile.saving': 'جاري الحفظ...',
    'profile.updated_success': '✅ تم تحديث الملف الشخصي بنجاح',
    'profile.save_error': 'حدث خطأ أثناء حفظ التغييرات',
    
    // Cart
    'cart.empty': 'السلة فارغة',
    'cart.title': 'سلة التسوق',
    'cart.subtotal': 'المجموع الفرعي',
    'cart.discount': 'الخصم',
    'cart.coupon': 'كود الخصم',
    'cart.apply_coupon': 'تطبيق',
    'cart.remove_coupon': 'إلغاء',
    'cart.checkout': 'إتمام الشراء',
    
    // Orders
    'orders.title': 'طلباتي',
    'orders.no_orders': 'لا توجد طلبات',
    'orders.order': 'طلب',
    'orders.order_number': 'رقم الطلب',
    'orders.date': 'التاريخ',
    'orders.status': 'الحالة',
    'orders.pending': 'قيد المعالجة',
    'orders.processing': 'جاري التجهيز',
    'orders.shipped': 'تم الشحن',
    'orders.completed': 'مكتمل',
    'orders.cancelled': 'ملغي',
    'orders.refunded': 'مسترجع',
    
    // Payment
    'payment.title': 'طرق الدفع',
    'payment.wallet': 'المحفظة الرقمية',
    'payment.crypto': 'العملات الرقمية',
    'payment.balance': 'الرصيد',
    'payment.deposit': 'إيداع',
    'payment.withdraw': 'سحب',
    'payment.transfer': 'تحويل',
    'payment.history': 'سجل المعاملات',
    'payment.bitcoin': 'بيتكوين',
    'payment.ethereum': 'إيثريوم',
    'payment.usdt': 'Tether (USDT)',
    'payment.paypal': 'PayPal',
    'payment.card': 'بطاقة ائتمان',
    
    // Wallet
    'wallet.title': 'محفظتي',
    'wallet.balance': 'الرصيد الحالي',
    'wallet.crypto_balance': 'رصيد العملات الرقمية',
    'wallet.deposit': 'إيداع',
    'wallet.withdraw': 'سحب',
    'wallet.transactions': 'المعاملات',
    'wallet.address': 'عنوان المحفظة',
    'wallet.copy_address': 'نسخ العنوان',
    
    // Notifications
    'notifications.title': 'الإشعارات',
    'notifications.mark_all_read': 'تحديد الكل كمقروء',
    'notifications.no_notifications': 'لا توجد إشعارات',
    'notifications.order_created': 'تم إنشاء طلب جديد',
    'notifications.order_updated': 'تم تحديث الطلب',
    'notifications.payment_received': 'تم استلام الدفع',
    'notifications.payment_failed': 'فشل الدفع',
    'notifications.wallet_credited': 'تم إيداع الرصيد',
    'notifications.wallet_debited': 'تم خصم الرصيد',
    'notifications.new_message': 'رسالة جديدة',
    'notifications.offer_available': 'عرض جديد متاح',
    
    // Footer
    'footer.quick_links': 'روابط سريعة',
    'footer.support': 'الدعم',
    'footer.terms': 'الشروط والأحكام',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.refund': 'سياسة الاسترجاع',
    'footer.copyright': 'جميع الحقوق محفوظة',
    
    // Contact
    'contact.title': 'اتصل بنا',
    'contact.desc': 'نحن هنا لمساعدتك',
    'contact.phone': 'الهاتف',
    'contact.email': 'البريد الإلكتروني',
    'contact.whatsapp': 'واتساب',
    'contact.send_message': 'أرسل رسالة',
    'contact.message': 'رسالتك',
    'contact.subject': 'الموضوع',
    'contact.send': 'إرسال',
    'contact.sent': 'تم الإرسال',
    'contact.thanks': 'شكراً لتواصلك معنا',
    
    // Support
    'support.title': 'مركز الدعم',
    'support.live_chat': 'دردشة مباشرة',
    'support.chat_desc': 'تحدث مع فريق الدعم',
    'support.start_chat': 'ابدأ المحادثة',
    
    // Recharge
    'recharge.title': 'شحن سريع',
    'recharge.desc': 'شحن فوري للألعاب والرصيد',
    'recharge.select_operator': 'اختر المشغل',
    'recharge.select_amount': 'اختر المبلغ',
    'recharge.phone_number': 'رقم الهاتف',
    'recharge.order_summary': 'ملخص الطلب',
    'recharge.operator': 'المشغل',
    'recharge.amount': 'المبلغ',
    'recharge.price': 'السعر',
    'recharge.confirm': 'تأكيد',
    
    // Admin
    'admin.dashboard': 'لوحة التحكم',
    'admin.users': 'المستخدمين',
    'admin.products': 'المنتجات',
    'admin.orders': 'الطلبات',
    'admin.payments': 'المدفوعات',
    'admin.wallets': 'المحافظ',
    'admin.settings': 'الإعدادات',
    'admin.notifications': 'الإشعارات',
    'admin.codes': 'الأكواد',
    'admin.giftcards': 'بطاقات الهدايا',
    'admin.offers': 'العروض',
    'admin.social': 'وسائل التواصل',
    'admin.chatbot': 'الشاربوت',
    'admin.sections': 'أقسام الموقع',
    'admin.overview': 'نظرة عامة',
    'admin.sellers': 'إدارة الباعة',
    'admin.finance': 'الفواتير والمخزون والزكاة',
    'admin.store': 'إدارة المتجر',
    'admin.ads': 'إدارة الإعلانات',
    'admin.ai_bots': 'البوتات الذكية',
    'admin.chatbots': 'الدردشة الذكية',
    'admin.apis': 'واجهات API',
    'admin.disputes': 'النزاعات',
    'admin.not_available': 'غير متوفر',
    'admin.connected': 'متصل',
    'admin.disconnected': 'غير متصل',
    'admin.users_count': 'المستخدمون',
    'admin.ctgpro_assistant': 'مساعد CTGPRO',
    'admin.ask_ai_hint': 'اسأل عن الطلبات، المخزون، الزكاة، والإعدادات',
    'admin.ai_prompt_placeholder': 'مثال: ما هي أفضل طريقة لإدارة المخزون اليوم؟',
    'admin.sending_to_ai': 'إرسال إلى CTGPRO',
    'admin.processing': 'جاري المعالجة...',
    'admin.bot_loading': 'جارٍ إعداد الإجابة...',
    'admin.bot_empty': 'ستظهر إجابة البوت هنا بعد إرسال سؤالك.',
    'admin.ai_product_create': 'إضافة منتج بالذكاء الاصطناعي',
    'admin.product_name': 'اسم المنتج',
    'admin.product_description': 'وصف المنتج',
    'admin.product_price': 'السعر',
    'admin.product_stock': 'المخزون',
    'admin.image_query_placeholder': 'مثال: صورة منتج شحن أو كرت هدايا',
    'admin.add_product_ai': 'إضافة المنتج بالذكاء الاصطناعي',
    'admin.adding_product': 'جاري الإضافة...',
    'admin.ask_bot_first': 'اكتب سؤالا للبوت اولا',
    'admin.no_answer': 'لا توجد إجابة',
    'admin.bot_unreachable': 'تعذر الاتصال بالبوت',
    'admin.enter_product_name_first': 'أدخل اسم المنتج أولا',
    'admin.product_added': 'تمت إضافة المنتج',
    'admin.product_added_success': 'تمت إضافة المنتج بنجاح',
    'admin.product_add_failed': 'تعذر إضافة المنتج',
    'admin.searching_for': 'جاري البحث عن: {query}',
    'admin.language_changed_to': 'تم تغيير اللغة إلى {language}',
    'admin.logout_success': 'تم تسجيل الخروج بنجاح',
    'admin.search_results': 'نتائج البحث',
    'admin.new_order': 'طلب جديد',
    'admin.order_status_message': 'طلب #{id} بحالة {status}',
    'admin.mark_all_read_success': 'تم تحديد جميع الإشعارات كمقروءة',
    'admin.notifications_update_failed': 'تعذر تحديث الإشعارات',
    'admin.view_all_notifications': 'عرض جميع الإشعارات',
    'admin.view_all_messages': 'عرض الكل',
    'admin.no_messages': 'لا توجد رسائل',
    'admin.login_title': 'تسجيل الدخول',
    'admin.login_subtitle': 'أدخل بياناتك للوصول إلى لوحة التحكم',
    'admin.email_required': 'الرجاء إدخال البريد الإلكتروني وكلمة المرور',
    'admin.welcome_back_admin': 'مرحبا بعودتك مدير',
    'admin.access_denied': 'غير مصرح لك بالوصول إلى لوحة التحكم',
    'admin.invalid_credentials': 'بيانات الدخول غير صحيحة',
    'admin.verifying': 'جاري التحقق...',
    'admin.protected_page': 'هذه الصفحة محمية، فقط المديرين يمكنهم الوصول',
    'admin.copyright': 'جميع الحقوق محفوظة',
    'admin.demo_credentials_hint': 'استخدم حساب admin@ctgpro.com / admin123',
    'admin.users_management': 'إدارة المستخدمين',
    'admin.users_management_desc': 'إدارة جميع المستخدمين المسجلين في المنصة',
    'admin.add_user': 'إضافة مستخدم',
    'admin.print': 'طباعة',
    'admin.export': 'تصدير',
    'admin.search_user_placeholder': 'بحث عن مستخدم...',
    'admin.all_roles': 'جميع الأدوار',
    'admin.role_user': 'مستخدم',
    'admin.role_seller': 'بائع',
    'admin.role_admin': 'مدير',
    'admin.all_statuses': 'جميع الحالات',
    'admin.status_active': 'نشط',
    'admin.status_inactive': 'غير نشط',
    'admin.filter': 'فلتر',
    'admin.user': 'المستخدم',
    'admin.email': 'البريد الإلكتروني',
    'admin.role': 'الدور',
    'admin.status': 'الحالة',
    'admin.registered_at': 'تاريخ التسجيل',
    'admin.actions': 'الإجراءات',
    'admin.no_users_match': 'لا توجد مستخدمين مطابقين للبحث',
    'admin.add_new_user': 'إضافة مستخدم جديد',
    'admin.name': 'الاسم',
    'admin.phone': 'الهاتف',
    'admin.password': 'كلمة المرور',
    'admin.cancel': 'إلغاء',
    'admin.save_user': 'حفظ المستخدم',
    'admin.saving': 'جاري الحفظ...',
    'admin.fetch_users_failed': 'حدث خطأ في جلب المستخدمين',
    'admin.user_status_updated': 'تم {action} المستخدم بنجاح',
    'admin.user_enabled': 'تفعيل',
    'admin.user_disabled': 'تعطيل',
    'admin.generic_error': 'حدث خطأ',
    'admin.users_export_success': 'تم تنزيل ملف المستخدمين بنجاح',
    'admin.user_create_success': 'تم إنشاء المستخدم بنجاح',
    'admin.user_create_failed': 'حدث خطأ أثناء إنشاء المستخدم',
    'admin.users_socket_restored': 'تم استعادة الاتصال بنظام المستخدمين',
    'admin.users_socket_reconnected': 'تم إعادة الاتصال بنظام المستخدمين',
    'admin.dispute_back': 'العودة إلى النزاعات',
    'admin.dispute_details': 'تفاصيل النزاع',
    'admin.dispute_details_desc': 'عرض تفاصيل النزاع وإدارة حالته.',
    'admin.resolve': 'تم الحل',
    'admin.close': 'إغلاق',
    'admin.dispute_title': 'عنوان النزاع',
    'admin.priority': 'الأولوية',
    'admin.description': 'الوصف',
    'admin.order_number': 'رقم الطلب',
    'admin.amount': 'المبلغ',
    'admin.seller': 'البائع',
    'admin.messages_log': 'سجل الرسائل',
    'admin.messages_log_desc': 'عرض المحادثات المرسلة ضمن النزاع.',
    'admin.no_messages_yet': 'لا توجد رسائل حتى الآن.',
    'admin.unknown': 'غير معروف',
    'admin.view_attachment': 'عرض المرفق',
    'admin.dispute_fetch_failed': 'فشل جلب بيانات النزاع',
    'admin.dispute_status_updated': 'تم تحديث حالة النزاع بنجاح',
    'admin.dispute_status_update_failed': 'فشل تحديث حالة النزاع',
    'admin.dispute_open': 'مفتوح',
    'admin.dispute_in_progress': 'قيد المعالجة',
    'admin.dispute_resolved': 'تم الحل',
    'admin.dispute_closed': 'مغلق',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.shop': 'Shop',
    'nav.about': 'About Us',
    'nav.contact': 'Contact Us',
    'nav.support': 'Support',
    'nav.faq': 'FAQ',
    'nav.topup': 'Game Top-up',
    'nav.giftcards': 'Gift Cards',
    'nav.cdkeys': 'CD Keys',
    'nav.gamecards': 'Subscriptions',
    'nav.recharge': 'Quick Recharge',
    'nav.wishlist': 'Wishlist',
    'nav.cart': 'Cart',
    'nav.login': 'Sign In',
    'nav.register': 'Sign Up',
    'nav.logout': 'Logout',
    'nav.search': 'Search',
    'nav.search_placeholder': 'Search for top-up, gift cards, game keys...',
    'nav.dashboard': 'Dashboard',
    'nav.seller_dashboard': 'Seller Dashboard',
    'nav.currency': 'Currency',
    'nav.language': 'Language',
    'nav.wallet': 'Wallet',
    'nav.my_account': 'My Account',
    'nav.my_orders': 'My Orders',
    'nav.light_mode': 'Light Mode',
    'nav.dark_mode': 'Dark Mode',
    'nav.instant_delivery': 'Instant delivery 24/7',
    'nav.security': '100% Security',
    'nav.live_support': 'Live support 24/7',
    'nav.free_shipping': 'Free shipping for orders over $50',
    'nav.system': 'System',
    'nav.profile': 'Profile',
    'nav.reports': 'Reports',
    'nav.admin_panel': 'Control Panel',
    'nav.system_admin': 'System Admin',
    
    // Common
    'common.add_to_cart': 'Add to Cart',
    'common.buy_now': 'Buy Now',
    'common.out_of_stock': 'Out of Stock',
    'common.in_stock': 'In Stock',
    'common.only_left': 'left',
    'common.quick_view': 'Quick View',
    'common.view_all': 'View All',
    'common.total': 'Total',
    'common.checkout': 'Checkout',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.continue': 'Continue',
    'common.loading': 'Loading...',
    'common.no_results': 'No results found',
    'common.search_results': 'Search Results',
    'common.secure_payment': '100% Secure Payments',
    'common.copied': 'Copied',
    'common.share': 'Share',
    
    // Product
    'product.price': 'Price',
    'product.platform': 'Platform',
    'product.delivery': 'Delivery',
    'product.stock': 'Stock',
    'product.rating': 'Rating',
    'product.reviews': 'Reviews',
    'product.description': 'Description',
    'product.seller': 'Seller',
    'product.quantity': 'Quantity',
    'product.discount': 'Discount',
    
    // Auth
    'auth.login_title': 'Sign In',
    'auth.login_desc': 'Welcome back! Sign in to your account',
    'auth.register_title': 'Create Account',
    'auth.register_desc': 'Join CTGPRO and enjoy a unique top-up experience',
    'auth.email_or_phone': 'Email or Phone Number',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.remember_me': 'Remember me',
    'auth.forgot_password': 'Forgot Password?',
    'auth.no_account': "Don't have an account?",
    'auth.have_account': 'Already have an account?',
    'auth.full_name': 'Full Name',
    'auth.phone': 'Phone Number',
    'auth.reset_password': 'Reset Password',
    'auth.reset_password_desc': 'Enter your new password',
    
    // Profile
    'profile.title': 'Profile',
    'profile.personal_info': 'Personal Information',
    'profile.full_name': 'Full Name',
    'profile.phone': 'Phone Number',
    'profile.email': 'Email Address',
    'profile.address': 'Address',
    'profile.street': 'Street',
    'profile.city': 'City',
    'profile.state': 'State',
    'profile.zip_code': 'Postal Code',
    'profile.country': 'Country',
    'profile.account_preferences': 'Account Preferences',
    'profile.language': 'Language',
    'profile.currency': 'Currency',
    'profile.theme': 'Theme',
    'profile.notifications': 'Account Notifications',
    'profile.save_changes': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.updated_success': '✅ Profile updated successfully',
    'profile.save_error': 'An error occurred while saving changes',
    'profile.role': 'Role',
    'profile.role_admin': 'Admin',
    'profile.role_seller': 'Seller',
    'profile.role_user': 'User',
    
    // Cart
    'cart.empty': 'Cart is empty',
    'cart.title': 'Shopping Cart',
    'cart.subtotal': 'Subtotal',
    'cart.discount': 'Discount',
    'cart.coupon': 'Coupon Code',
    'cart.apply_coupon': 'Apply',
    'cart.remove_coupon': 'Remove',
    'cart.checkout': 'Checkout',
    
    // Orders
    'orders.title': 'My Orders',
    'orders.no_orders': 'No orders found',
    'orders.order': 'Order',
    'orders.order_number': 'Order Number',
    'orders.date': 'Date',
    'orders.status': 'Status',
    'orders.pending': 'Pending',
    'orders.processing': 'Processing',
    'orders.shipped': 'Shipped',
    'orders.completed': 'Completed',
    'orders.cancelled': 'Cancelled',
    'orders.refunded': 'Refunded',
    
    // Payment
    'payment.title': 'Payment Methods',
    'payment.wallet': 'Digital Wallet',
    'payment.crypto': 'Cryptocurrency',
    'payment.balance': 'Balance',
    'payment.deposit': 'Deposit',
    'payment.withdraw': 'Withdraw',
    'payment.transfer': 'Transfer',
    'payment.history': 'Transaction History',
    'payment.bitcoin': 'Bitcoin',
    'payment.ethereum': 'Ethereum',
    'payment.usdt': 'Tether (USDT)',
    'payment.paypal': 'PayPal',
    'payment.card': 'Credit Card',
    
    // Wallet
    'wallet.title': 'My Wallet',
    'wallet.balance': 'Current Balance',
    'wallet.crypto_balance': 'Crypto Balance',
    'wallet.deposit': 'Deposit',
    'wallet.withdraw': 'Withdraw',
    'wallet.transactions': 'Transactions',
    'wallet.address': 'Wallet Address',
    'wallet.copy_address': 'Copy Address',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.mark_all_read': 'Mark all as read',
    'notifications.no_notifications': 'No notifications',
    'notifications.order_created': 'New order created',
    'notifications.order_updated': 'Order updated',
    'notifications.payment_received': 'Payment received',
    'notifications.payment_failed': 'Payment failed',
    'notifications.wallet_credited': 'Wallet credited',
    'notifications.wallet_debited': 'Wallet debited',
    'notifications.new_message': 'New message',
    'notifications.offer_available': 'New offer available',
    
    // Footer
    'footer.quick_links': 'Quick Links',
    'footer.support': 'Support',
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.refund': 'Refund Policy',
    'footer.copyright': 'All rights reserved',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.desc': "We're here to help",
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.whatsapp': 'WhatsApp',
    'contact.send_message': 'Send a message',
    'contact.message': 'Your Message',
    'contact.subject': 'Subject',
    'contact.send': 'Send',
    'contact.sent': 'Sent',
    'contact.thanks': 'Thank you for contacting us',
    
    // Support
    'support.title': 'Support Center',
    'support.live_chat': 'Live Chat',
    'support.chat_desc': 'Talk to support team',
    'support.start_chat': 'Start Chat',
    
    // Recharge
    'recharge.title': 'Quick Recharge',
    'recharge.desc': 'Instant game and mobile recharge',
    'recharge.select_operator': 'Select Operator',
    'recharge.select_amount': 'Select Amount',
    'recharge.phone_number': 'Phone Number',
    'recharge.order_summary': 'Order Summary',
    'recharge.operator': 'Operator',
    'recharge.amount': 'Amount',
    'recharge.price': 'Price',
    'recharge.confirm': 'Confirm',
    
    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.products': 'Products',
    'admin.orders': 'Orders',
    'admin.payments': 'Payments',
    'admin.wallets': 'Wallets',
    'admin.settings': 'Settings',
    'admin.notifications': 'Notifications',
    'admin.codes': 'Codes',
    'admin.giftcards': 'Gift Cards',
    'admin.offers': 'Offers',
    'admin.social': 'Social Media',
    'admin.chatbot': 'Chatbot',
    'admin.sections': 'Sections',
    'admin.overview': 'Overview',
    'admin.sellers': 'Sellers Management',
    'admin.finance': 'Billing, Inventory and Zakat',
    'admin.store': 'Store Management',
    'admin.ads': 'Ads Management',
    'admin.ai_bots': 'AI Bots',
    'admin.chatbots': 'Smart Chat',
    'admin.apis': 'API Endpoints',
    'admin.disputes': 'Disputes',
    'admin.not_available': 'Not available',
    'admin.connected': 'Connected',
    'admin.disconnected': 'Disconnected',
    'admin.users_count': 'Users',
    'admin.ctgpro_assistant': 'CTGPRO Assistant',
    'admin.ask_ai_hint': 'Ask about orders, inventory, zakat, and settings',
    'admin.ai_prompt_placeholder': 'Example: What is the best way to manage inventory today?',
    'admin.sending_to_ai': 'Send to CTGPRO',
    'admin.processing': 'Processing...',
    'admin.bot_loading': 'Preparing answer...',
    'admin.bot_empty': 'The bot answer will appear here after sending your question.',
    'admin.ai_product_create': 'Create Product with AI',
    'admin.product_name': 'Product Name',
    'admin.product_description': 'Product Description',
    'admin.product_price': 'Price',
    'admin.product_stock': 'Stock',
    'admin.image_query_placeholder': 'Example: top-up or gift card product image',
    'admin.add_product_ai': 'Add Product with AI',
    'admin.adding_product': 'Adding...',
    'admin.ask_bot_first': 'Write a question for the bot first',
    'admin.no_answer': 'No answer found',
    'admin.bot_unreachable': 'Unable to reach bot',
    'admin.enter_product_name_first': 'Enter product name first',
    'admin.product_added': 'Product added',
    'admin.product_added_success': 'Product added successfully',
    'admin.product_add_failed': 'Failed to add product',
    'admin.searching_for': 'Searching for: {query}',
    'admin.language_changed_to': 'Language changed to {language}',
    'admin.logout_success': 'Logged out successfully',
    'admin.search_results': 'Search results',
    'admin.new_order': 'New order',
    'admin.order_status_message': 'Order #{id} with status {status}',
    'admin.mark_all_read_success': 'All notifications marked as read',
    'admin.notifications_update_failed': 'Unable to update notifications',
    'admin.view_all_notifications': 'View all notifications',
    'admin.view_all_messages': 'View all',
    'admin.no_messages': 'No messages',
    'admin.login_title': 'Admin Sign In',
    'admin.login_subtitle': 'Enter your credentials to access the control panel',
    'admin.email_required': 'Please enter email and password',
    'admin.welcome_back_admin': 'Welcome back, admin',
    'admin.access_denied': 'You are not allowed to access the control panel',
    'admin.invalid_credentials': 'Invalid credentials',
    'admin.verifying': 'Verifying...',
    'admin.protected_page': 'This page is protected. Only admins can access it',
    'admin.copyright': 'All rights reserved',
    'admin.demo_credentials_hint': 'Use account admin@ctgpro.com / admin123',
    'admin.users_management': 'Users Management',
    'admin.users_management_desc': 'Manage all registered platform users',
    'admin.add_user': 'Add User',
    'admin.print': 'Print',
    'admin.export': 'Export',
    'admin.search_user_placeholder': 'Search user...',
    'admin.all_roles': 'All roles',
    'admin.role_user': 'User',
    'admin.role_seller': 'Seller',
    'admin.role_admin': 'Admin',
    'admin.all_statuses': 'All statuses',
    'admin.status_active': 'Active',
    'admin.status_inactive': 'Inactive',
    'admin.filter': 'Filter',
    'admin.user': 'User',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.status': 'Status',
    'admin.registered_at': 'Registered at',
    'admin.actions': 'Actions',
    'admin.no_users_match': 'No users match your search',
    'admin.add_new_user': 'Add New User',
    'admin.name': 'Name',
    'admin.phone': 'Phone',
    'admin.password': 'Password',
    'admin.cancel': 'Cancel',
    'admin.save_user': 'Save User',
    'admin.saving': 'Saving...',
    'admin.fetch_users_failed': 'Failed to load users',
    'admin.user_status_updated': 'User {action} successfully',
    'admin.user_enabled': 'enabled',
    'admin.user_disabled': 'disabled',
    'admin.generic_error': 'An error occurred',
    'admin.users_export_success': 'Users file downloaded successfully',
    'admin.user_create_success': 'User created successfully',
    'admin.user_create_failed': 'Error while creating user',
    'admin.users_socket_restored': 'Connection to users system restored',
    'admin.users_socket_reconnected': 'Reconnected to users system',
    'admin.dispute_back': 'Back to disputes',
    'admin.dispute_details': 'Dispute Details',
    'admin.dispute_details_desc': 'View dispute details and manage its status.',
    'admin.resolve': 'Resolve',
    'admin.close': 'Close',
    'admin.dispute_title': 'Dispute Title',
    'admin.priority': 'Priority',
    'admin.description': 'Description',
    'admin.order_number': 'Order Number',
    'admin.amount': 'Amount',
    'admin.seller': 'Seller',
    'admin.messages_log': 'Messages Log',
    'admin.messages_log_desc': 'View messages exchanged in this dispute.',
    'admin.no_messages_yet': 'No messages yet.',
    'admin.unknown': 'Unknown',
    'admin.view_attachment': 'View Attachment',
    'admin.dispute_fetch_failed': 'Failed to load dispute data',
    'admin.dispute_status_updated': 'Dispute status updated successfully',
    'admin.dispute_status_update_failed': 'Failed to update dispute status',
    'admin.dispute_open': 'Open',
    'admin.dispute_in_progress': 'In progress',
    'admin.dispute_resolved': 'Resolved',
    'admin.dispute_closed': 'Closed',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.shop': 'Boutique',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.support': 'Support',
    'nav.faq': 'FAQ',
    'nav.topup': 'Recharge de jeux',
    'nav.giftcards': 'Cartes cadeaux',
    'nav.cdkeys': 'Clés CD',
    'nav.gamecards': 'Abonnements',
    'nav.recharge': 'Recharge rapide',
    'nav.wishlist': 'Favoris',
    'nav.cart': 'Panier',
    'nav.login': 'Connexion',
    'nav.register': 'S\'inscrire',
    'nav.logout': 'Déconnexion',
    'nav.search': 'Rechercher',
    'nav.search_placeholder': 'Rechercher recharge, cartes cadeaux...',
    'nav.dashboard': 'Tableau',
    'nav.seller_dashboard': 'Tableau vendeur',
    'nav.currency': 'Devise',
    'nav.language': 'Langue',
    'nav.wallet': 'Portefeuille',
    'nav.my_account': 'Mon compte',
    'nav.my_orders': 'Mes commandes',
    'nav.light_mode': 'Mode clair',
    'nav.dark_mode': 'Mode nuit',
    'nav.instant_delivery': 'Livraison instantanee 24/7',
    'nav.security': 'Securite 100%',
    'nav.live_support': 'Support en direct 24/7',
    'nav.free_shipping': 'Livraison gratuite pour les commandes de plus de $50',
    'nav.system': 'Systeme',
    'nav.profile': 'Profil',
    'nav.reports': 'Rapports',
    'nav.admin_panel': 'Panneau de controle',
    'nav.system_admin': 'Administrateur systeme',
    
    // Common
    'common.add_to_cart': 'Ajouter au panier',
    'common.buy_now': 'Acheter maintenant',
    'common.out_of_stock': 'Rupture de stock',
    'common.in_stock': 'En stock',
    'common.only_left': 'restant',
    'common.quick_view': 'Aperçu rapide',
    'common.view_all': 'Voir tout',
    'common.total': 'Total',
    'common.checkout': 'Paiement',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.save': 'Enregistrer',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.close': 'Fermer',
    'common.back': 'Retour',
    'common.continue': 'Continuer',
    'common.loading': 'Chargement...',
    'common.no_results': 'Aucun résultat',
    'common.search_results': 'Résultats de recherche',
    'common.secure_payment': 'Paiements sécurisés 100%',
    'common.copied': 'Copié',
    'common.share': 'Partager',
    
    // Product
    'product.price': 'Prix',
    'product.platform': 'Plateforme',
    'product.delivery': 'Livraison',
    'product.stock': 'Stock',
    'product.rating': 'Évaluation',
    'product.reviews': 'Avis',
    'product.description': 'Description',
    'product.seller': 'Vendeur',
    'product.quantity': 'Quantité',
    'product.discount': 'Réduction',
    
    // Auth
    'auth.login_title': 'Connexion',
    'auth.login_desc': 'Bon retour! Connectez-vous',
    'auth.register_title': 'Créer un compte',
    'auth.register_desc': 'Rejoignez CTGPRO',
    'auth.email_or_phone': 'Email ou téléphone',
    'auth.password': 'Mot de passe',
    'auth.confirm_password': 'Confirmer',
    'auth.remember_me': 'Se souvenir',
    'auth.forgot_password': 'Mot de passe oublié?',
    'auth.no_account': 'Pas de compte?',
    'auth.have_account': 'Déjà un compte?',
    'auth.full_name': 'Nom complet',
    'auth.phone': 'Téléphone',
    'auth.reset_password': 'Réinitialiser le mot de passe',
    'auth.reset_password_desc': 'Entrez votre nouveau mot de passe',
    
    // Profile
    'profile.title': 'Profil',
    'profile.personal_info': 'Informations personnelles',
    'profile.full_name': 'Nom complet',
    'profile.phone': 'Numéro de téléphone',
    'profile.email': 'Adresse e-mail',
    'profile.address': 'Adresse',
    'profile.street': 'Rue',
    'profile.city': 'Ville',
    'profile.state': 'Région',
    'profile.zip_code': 'Code postal',
    'profile.country': 'Pays',
    'profile.account_preferences': 'Préférences du compte',
    'profile.language': 'Langue',
    'profile.currency': 'Devise',
    'profile.theme': 'Thème',
    'profile.notifications': 'Notifications du compte',
    'profile.save_changes': 'Enregistrer les modifications',
    'profile.saving': 'Enregistrement...',
    'profile.updated_success': '✅ Profil mis à jour avec succès',
    'profile.save_error': 'Une erreur est survenue lors de l’enregistrement',
    'profile.role': 'Rôle',
    'profile.role_admin': 'Administrateur',
    'profile.role_seller': 'Vendeur',
    'profile.role_user': 'Utilisateur',
    
    // Cart
    'cart.empty': 'Panier vide',
    'cart.title': 'Panier',
    'cart.subtotal': 'Sous-total',
    'cart.discount': 'Réduction',
    'cart.coupon': 'Code promo',
    'cart.apply_coupon': 'Appliquer',
    'cart.remove_coupon': 'Supprimer',
    'cart.checkout': 'Paiement',
    
    // Orders
    'orders.title': 'Mes commandes',
    'orders.no_orders': 'Aucune commande',
    'orders.order': 'Commande',
    'orders.order_number': 'Numéro',
    'orders.date': 'Date',
    'orders.status': 'Statut',
    'orders.pending': 'En attente',
    'orders.processing': 'En traitement',
    'orders.shipped': 'Expédié',
    'orders.completed': 'Terminé',
    'orders.cancelled': 'Annulé',
    'orders.refunded': 'Remboursé',
    
    // Payment
    'payment.title': 'Méthodes de paiement',
    'payment.wallet': 'Portefeuille numérique',
    'payment.crypto': 'Cryptomonnaie',
    'payment.balance': 'Solde',
    'payment.deposit': 'Dépôt',
    'payment.withdraw': 'Retrait',
    'payment.transfer': 'Transfert',
    'payment.history': 'Historique',
    'payment.bitcoin': 'Bitcoin',
    'payment.ethereum': 'Ethereum',
    'payment.usdt': 'Tether (USDT)',
    'payment.paypal': 'PayPal',
    'payment.card': 'Carte de crédit',
    
    // Wallet
    'wallet.title': 'Mon portefeuille',
    'wallet.balance': 'Solde actuel',
    'wallet.crypto_balance': 'Solde crypto',
    'wallet.deposit': 'Dépôt',
    'wallet.withdraw': 'Retrait',
    'wallet.transactions': 'Transactions',
    'wallet.address': 'Adresse',
    'wallet.copy_address': 'Copier',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.mark_all_read': 'Tout marquer comme lu',
    'notifications.no_notifications': 'Aucune notification',
    'notifications.order_created': 'Nouvelle commande',
    'notifications.order_updated': 'Commande mise à jour',
    'notifications.payment_received': 'Paiement reçu',
    'notifications.payment_failed': 'Paiement échoué',
    'notifications.wallet_credited': 'Portefeuille crédité',
    'notifications.wallet_debited': 'Portefeuille débité',
    'notifications.new_message': 'Nouveau message',
    'notifications.offer_available': 'Nouvelle offre',
    
    // Footer
    'footer.quick_links': 'Liens rapides',
    'footer.support': 'Support',
    'footer.terms': 'Conditions',
    'footer.privacy': 'Confidentialité',
    'footer.refund': 'Remboursement',
    'footer.copyright': 'Tous droits réservés',
    
    // Contact
    'contact.title': 'Contactez-nous',
    'contact.desc': 'Nous sommes là pour vous aider',
    'contact.phone': 'Téléphone',
    'contact.email': 'Email',
    'contact.whatsapp': 'WhatsApp',
    'contact.send_message': 'Envoyer un message',
    'contact.message': 'Votre message',
    'contact.subject': 'Sujet',
    'contact.send': 'Envoyer',
    'contact.sent': 'Envoyé',
    'contact.thanks': 'Merci de nous contacter',
    
    // Support
    'support.title': 'Centre d\'aide',
    'support.live_chat': 'Chat en direct',
    'support.chat_desc': 'Parlez à l\'équipe',
    'support.start_chat': 'Démarrer le chat',
    
    // Recharge
    'recharge.title': 'Recharge rapide',
    'recharge.desc': 'Recharge instantanée',
    'recharge.select_operator': 'Choisir l\'opérateur',
    'recharge.select_amount': 'Choisir le montant',
    'recharge.phone_number': 'Numéro de téléphone',
    'recharge.order_summary': 'Résumé',
    'recharge.operator': 'Opérateur',
    'recharge.amount': 'Montant',
    'recharge.price': 'Prix',
    'recharge.confirm': 'Confirmer',
    
    // Admin
    'admin.dashboard': 'Tableau de bord',
    'admin.users': 'Utilisateurs',
    'admin.products': 'Produits',
    'admin.orders': 'Commandes',
    'admin.payments': 'Paiements',
    'admin.wallets': 'Portefeuilles',
    'admin.settings': 'Paramètres',
    'admin.notifications': 'Notifications',
    'admin.codes': 'Codes',
    'admin.giftcards': 'Cartes cadeaux',
    'admin.offers': 'Offres',
    'admin.social': 'Réseaux sociaux',
    'admin.chatbot': 'Chatbot',
    'admin.sections': 'Sections',
    'admin.overview': 'Vue d ensemble',
    'admin.sellers': 'Gestion des vendeurs',
    'admin.finance': 'Facturation, stock et zakat',
    'admin.store': 'Gestion de la boutique',
    'admin.ads': 'Gestion des publicites',
    'admin.ai_bots': 'Bots IA',
    'admin.chatbots': 'Chat intelligent',
    'admin.apis': 'Interfaces API',
    'admin.disputes': 'Litiges',
    'admin.not_available': 'Non disponible',
    'admin.connected': 'Connecte',
    'admin.disconnected': 'Deconnecte',
    'admin.users_count': 'Utilisateurs',
    'admin.ctgpro_assistant': 'Assistant CTGPRO',
    'admin.ask_ai_hint': 'Posez des questions sur commandes, stock, zakat et parametres',
    'admin.ai_prompt_placeholder': 'Exemple : Quelle est la meilleure facon de gerer le stock aujourd hui ?',
    'admin.sending_to_ai': 'Envoyer a CTGPRO',
    'admin.processing': 'Traitement...',
    'admin.bot_loading': 'Preparation de la reponse...',
    'admin.bot_empty': 'La reponse du bot apparaitra ici apres envoi de votre question.',
    'admin.ai_product_create': 'Ajouter un produit avec IA',
    'admin.product_name': 'Nom du produit',
    'admin.product_description': 'Description du produit',
    'admin.product_price': 'Prix',
    'admin.product_stock': 'Stock',
    'admin.image_query_placeholder': 'Exemple : image produit recharge ou carte cadeau',
    'admin.add_product_ai': 'Ajouter le produit avec IA',
    'admin.adding_product': 'Ajout en cours...',
    'admin.ask_bot_first': 'Ecrivez d abord une question au bot',
    'admin.no_answer': 'Aucune reponse',
    'admin.bot_unreachable': 'Impossible de contacter le bot',
    'admin.enter_product_name_first': 'Entrez d abord le nom du produit',
    'admin.product_added': 'Produit ajoute',
    'admin.product_added_success': 'Produit ajoute avec succes',
    'admin.product_add_failed': 'Echec de l ajout du produit',
    'admin.searching_for': 'Recherche de : {query}',
    'admin.language_changed_to': 'Langue changee en {language}',
    'admin.logout_success': 'Deconnexion reussie',
    'admin.search_results': 'Resultats de recherche',
    'admin.new_order': 'Nouvelle commande',
    'admin.order_status_message': 'Commande #{id} avec statut {status}',
    'admin.mark_all_read_success': 'Toutes les notifications sont marquees comme lues',
    'admin.notifications_update_failed': 'Impossible de mettre a jour les notifications',
    'admin.view_all_notifications': 'Voir toutes les notifications',
    'admin.view_all_messages': 'Voir tout',
    'admin.no_messages': 'Aucun message',
    'admin.login_title': 'Connexion admin',
    'admin.login_subtitle': 'Entrez vos informations pour acceder au panneau de controle',
    'admin.email_required': 'Veuillez saisir email et mot de passe',
    'admin.welcome_back_admin': 'Bon retour, admin',
    'admin.access_denied': 'Vous n etes pas autorise a acceder au panneau de controle',
    'admin.invalid_credentials': 'Identifiants invalides',
    'admin.verifying': 'Verification...',
    'admin.protected_page': 'Cette page est protegee. Seuls les admins peuvent y acceder',
    'admin.copyright': 'Tous droits reserves',
    'admin.demo_credentials_hint': 'Utilisez le compte admin@ctgpro.com / admin123',
    'admin.users_management': 'Gestion des utilisateurs',
    'admin.users_management_desc': 'Gerer tous les utilisateurs inscrits',
    'admin.add_user': 'Ajouter un utilisateur',
    'admin.print': 'Imprimer',
    'admin.export': 'Exporter',
    'admin.search_user_placeholder': 'Rechercher un utilisateur...',
    'admin.all_roles': 'Tous les roles',
    'admin.role_user': 'Utilisateur',
    'admin.role_seller': 'Vendeur',
    'admin.role_admin': 'Administrateur',
    'admin.all_statuses': 'Tous les statuts',
    'admin.status_active': 'Actif',
    'admin.status_inactive': 'Inactif',
    'admin.filter': 'Filtrer',
    'admin.user': 'Utilisateur',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.status': 'Statut',
    'admin.registered_at': 'Date d inscription',
    'admin.actions': 'Actions',
    'admin.no_users_match': 'Aucun utilisateur ne correspond a la recherche',
    'admin.add_new_user': 'Ajouter un nouvel utilisateur',
    'admin.name': 'Nom',
    'admin.phone': 'Telephone',
    'admin.password': 'Mot de passe',
    'admin.cancel': 'Annuler',
    'admin.save_user': 'Enregistrer utilisateur',
    'admin.saving': 'Enregistrement...',
    'admin.fetch_users_failed': 'Echec du chargement des utilisateurs',
    'admin.user_status_updated': 'Utilisateur {action} avec succes',
    'admin.user_enabled': 'active',
    'admin.user_disabled': 'desactive',
    'admin.generic_error': 'Une erreur est survenue',
    'admin.users_export_success': 'Fichier utilisateurs telecharge avec succes',
    'admin.user_create_success': 'Utilisateur cree avec succes',
    'admin.user_create_failed': 'Erreur lors de la creation de l utilisateur',
    'admin.users_socket_restored': 'Connexion au systeme utilisateurs restauree',
    'admin.users_socket_reconnected': 'Reconnexion au systeme utilisateurs',
    'admin.dispute_back': 'Retour aux litiges',
    'admin.dispute_details': 'Details du litige',
    'admin.dispute_details_desc': 'Afficher les details du litige et gerer son statut.',
    'admin.resolve': 'Resolu',
    'admin.close': 'Fermer',
    'admin.dispute_title': 'Titre du litige',
    'admin.priority': 'Priorite',
    'admin.description': 'Description',
    'admin.order_number': 'Numero de commande',
    'admin.amount': 'Montant',
    'admin.seller': 'Vendeur',
    'admin.messages_log': 'Historique des messages',
    'admin.messages_log_desc': 'Afficher les messages echanges dans ce litige.',
    'admin.no_messages_yet': 'Aucun message pour le moment.',
    'admin.unknown': 'Inconnu',
    'admin.view_attachment': 'Voir la piece jointe',
    'admin.dispute_fetch_failed': 'Echec du chargement des donnees du litige',
    'admin.dispute_status_updated': 'Statut du litige mis a jour avec succes',
    'admin.dispute_status_update_failed': 'Echec de la mise a jour du statut du litige',
    'admin.dispute_open': 'Ouvert',
    'admin.dispute_in_progress': 'En cours',
    'admin.dispute_resolved': 'Resolu',
    'admin.dispute_closed': 'Ferme',
  },
};

export const LanguageProvider = ({ children }) => {
  const normalizeLang = (lang) => {
    if (!lang) return 'ar';
    // accept codes like 'en', 'en-US', 'fr-FR' -> map to supported keys
    const base = String(lang).split('-')[0];
    return SUPPORTED_LANGUAGES[base] ? base : 'ar';
  };

  const [language, _setLanguage] = useState(() => {
    // Allow overriding via URL param ?lang=fr or ?lang=en-US for quick testing
    try {
      const params = typeof window !== 'undefined' ? new URLSearchParams(window.location.search) : null;
      const urlLang = params?.get('lang');
      if (urlLang) return normalizeLang(urlLang);
    } catch (e) {
      // ignore
    }
    return normalizeLang(localStorage.getItem('ctgpro_language') || 'ar');
  });

  const { registerRestoreHandler, user } = useAuth();
  const userRef = useRef(user);

  const [currency, setCurrency] = useState(() => {
    return localStorage.getItem('ctgpro_currency') || 'USD';
  });

  useEffect(() => {
    userRef.current = user;
  }, [user]);

  useEffect(() => {
    const normalized = normalizeLang(language);
    localStorage.setItem('ctgpro_language', normalized);
    const currentLanguage = SUPPORTED_LANGUAGES[normalized];
    document.documentElement.dir = currentLanguage?.dir || 'ltr';
    document.documentElement.lang = normalized;
    if (normalized !== language) {
      // keep state normalized
      _setLanguage(normalized);
    }
    // debug helper during development
    if (process.env.NODE_ENV === 'development') {
      // eslint-disable-next-line no-console
      console.debug('[LanguageProvider] active language:', normalized);
    }
  }, [language]);

  useEffect(() => {
    localStorage.setItem('ctgpro_currency', currency);
  }, [currency]);

  useEffect(() => {
    if (!registerRestoreHandler) return;

    const handler = () => {
      const preferences = userRef.current?.preferences;
      if (preferences?.language && SUPPORTED_LANGUAGES[preferences.language]) {
        setLanguage(preferences.language);
      }
      if (preferences?.currency && SUPPORTED_CURRENCIES[preferences.currency]) {
        setCurrency(preferences.currency);
      }
    };

    const unregister = registerRestoreHandler(handler);
    return unregister;
  }, [registerRestoreHandler]);

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  const formatCurrency = (amount) => {
    const rates = {
      USD: 1,
      EUR: 0.92,
      GBP: 0.79,
      DZD: 135.0,
      SAR: 3.75,
      AED: 3.67,
      BTC: 0.000015,
      ETH: 0.00023,
      USDT: 1,
    };
    
    const symbols = {
      USD: '$',
      EUR: '€',
      GBP: '£',
      DZD: 'دج',
      SAR: 'ر.س',
      AED: 'د.إ',
      BTC: '₿',
      ETH: 'Ξ',
      USDT: '₮',
    };

    const rate = rates[currency] || 1;
    const symbol = symbols[currency] || '$';
    const converted = amount * rate;

    if (currency === 'BTC' || currency === 'ETH') {
      return `${symbol}${converted.toFixed(6)}`;
    }
    return `${symbol}${converted.toFixed(2)}`;
  };

  const getCurrencySymbol = () => {
    const symbols = {
      USD: '$',
      EUR: '€',
      GBP: '£',
      DZD: 'دج',
      SAR: 'ر.س',
      AED: 'د.إ',
      BTC: '₿',
      ETH: 'Ξ',
      USDT: '₮',
    };
    return symbols[currency] || '$';
  };

  const getCurrencyCode = () => currency;
  const getLanguageCode = () => language;
  
  const getLanguageName = () => {
    return SUPPORTED_LANGUAGES[language]?.name || 'العربية';
  };
  
  const getLanguageFlag = () => {
    return SUPPORTED_LANGUAGES[language]?.flag || '🌐';
  };
  
  const getCurrencyFlag = () => {
    const flags = {
      USD: '🇺🇸',
      EUR: '🇪🇺',
      GBP: '🇬🇧',
      DZD: '🇩🇿',
      SAR: '🇸🇦',
      AED: '🇦🇪',
      BTC: '₿',
      ETH: 'Ξ',
      USDT: '₮',
    };
    return flags[currency] || '💵';
  };

  const setLanguage = (code) => {
    const normalized = normalizeLang(code);
    _setLanguage(normalized);
  };

  const value = {
    language,
    setLanguage,
    currency,
    setCurrency,
    t,
    formatCurrency,
    getCurrencySymbol,
    getCurrencyCode,
    getLanguageCode,
    getLanguageName,
    getLanguageFlag,
    getCurrencyFlag,
    SUPPORTED_CURRENCIES,
    SUPPORTED_LANGUAGES,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};